[package]
name = "extractors"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }
unicode-segmentation = { workspace = true }
indexmap = { workspace = true }
uuid = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
console_error_panic_hook = { workspace = true }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]